services:
  chromadb:
    image: chromadb/chroma:latest # or a specific version like chromadb/chroma:0.5.2
    environment:
      - IS_PERSISTENT=TRUE # Enable persistence
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-FALSE} # Disable telemetry by default
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    volumes:
      - chroma_data:/chroma_data/chroma # Mount a named volume for data persistence
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - chromanet
  db:
      image: postgres:16-alpine # Or a specific version like postgres:17.2-alpine
      container_name: postgres_db
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: humanafterall
        POSTGRES_DB: reviews_db
      volumes:
        - pgdata:/var/lib/postgresql/data
      ports:
        - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: humanafterall
    ports:
      - "8080:80" # Access pgAdmin at http://localhost:8080
    depends_on:
      - db

volumes:
  pgdata:
  chroma_data:

networks:
  chromanet:
    driver: bridge