services:
  chromadb:
    image: chromadb/chroma:latest # or a specific version like chromadb/chroma:0.5.2
    environment:
      - IS_PERSISTENT=TRUE # Enable persistence
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-FALSE} # Disable telemetry by default
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    volumes:
      - chroma_data:/chroma_data/chroma # Mount a named volume for data persistence
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - chromanet

volumes:
  chroma_data:

networks:
  chromanet:
    driver: bridge